# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Read the Docs configuration file
version: 2

build:
  os: ubuntu-22.04        # ok to keep; 24.04 also works
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - echo "Using .readthedocs.yaml:"
      - cat .readthedocs.yaml

sphinx:
  configuration: docs/rst/conf.py
  builder: html
  fail_on_warning: false   # avoids failing on harmless warnings

# Build additional formats (RTD will run Sphinx latexpdf for this)
formats:
  - pdf

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - build
        - docs
